DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS(
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT null,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL  
)

--CREATE
INSERT INTO TB_HEROIS(NOME, PODER)
VALUES
  ('Flash', 'Velocidade'),
  ('Superman', 'Força'),
  ('Batman', 'Inteligência')

--READ
SELECT * FROM TB_HEROIS

--UPDATE
UPDATE TB_HEROIS
SET NOME = 'Arlequina', PODER='Trapaças'
WHERE ID = 3;

--DELETE
DELETE FROM TB_HEROIS WHERE ID=2
